plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev' version '7.1.25'
}

version = project.mod_version
base.archivesName = project.archives_base_name + '-neoforge'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencies {
    implementation project(':common')
    implementation "net.neoforged:neoforge:${project.neoforge_version}"
}

processResources {
    inputs.property "version", project.version
    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": version
    }
}

jar {
    dependsOn project(':common').jar
    from(project(':common').sourceSets.main.output)
    from(rootProject.file("LICENSE")) {
        rename { "${it}_${base.archivesName.get()}" }
    }
}

build.doLast {
    copy {
        from "build/libs/${base.archivesName.get()}-${version}.jar"
        into rootProject.file("Releases")
    }
}
